apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ryjz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ryjz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ryjz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ryjz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ryjz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zurd-tenant/rhtap-demo-app/hacbs-test-project-ryjz@sha256:fcd354177e24a1f8a8bc6f70b9c5d0b03f7f2f58091fc1de605ba67eb85b3e0b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
