apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ryjz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zurd-tenant/rhtap-demo-app/hacbs-test-project-ryjz@sha256:3b9f5d5707d179dcae67b30d0f942e74e2205ce561b24dd376706de67ef9f5ed
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
